-- Conteúdo inicial da Ajuda dos guias (editável no Painel ADM, em Conteúdo).

INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('faq', 'Convites e escalas', 'Como recebo convites para trabalhar?', 'Mantenha sua Disponibilidade em dia e seu Perfil completo (funções, idiomas e regiões). Quando a equipe escalar você, o convite aparece em Viagens/Tours e chega por e-mail. Aceite ou recuse o quanto antes para a equipe fechar a escala.', 1, 1);
INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('faq', 'Convites e escalas', 'Aceitei um convite. Onde vejo os detalhes?', 'Abra a viagem/tour em Viagens/Tours. Depois de aceitar, você vê o briefing completo: origens e horários, ponto de encontro, roteiro, regras, contatos da coordenação, do motorista e do guia local, e a lista de passageiros.', 2, 1);
INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('faq', 'Em campo', 'Como faço o check-in e o check-out dos passageiros?', 'Na viagem/tour, toque em "Lista de passageiros e mapa do carro". Na aba Lista, toque em Check-in quando o passageiro embarcar e em Check-out no desembarque. No Mapa do carro, toque na poltrona para ver o passageiro, ligar para ele ou fazer o check-in da reserva inteira. Sem internet, as marcações ficam guardadas e são enviadas quando o sinal voltar.', 3, 1);
INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('faq', 'Em campo', 'Um passageiro trocou de poltrona ou de embarque. O que faço?', 'Toque em Editar no passageiro e corrija. Sua alteração fica destacada em amarelo, o dado original é preservado e a coordenação recebe um e-mail. Se alguém entrou na última hora, use "Incluir passageiro".', 4, 1);
INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('faq', 'Imprevistos', 'Tive um imprevisto e não vou poder comparecer.', 'Avise o quanto antes, de preferência com 24 horas de antecedência: em Ajuda, abra um chamado com o assunto "Imprevisto / não poderei comparecer" e marque como urgente. Assim a equipe chama outro guia sem prejudicar o grupo.', 5, 1);
INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('faq', 'Depois do trabalho', 'Quando e como envio o relatório da viagem?', 'No último dia de trabalho, abra a viagem/tour e escreva o relatório: como foi o grupo, pontualidade, ocorrências, feedback e quantos passageiros foram atendidos. O relatório libera a etapa da nota fiscal.', 6, 1);
INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('faq', 'Nota fiscal e pagamento', 'Como envio a nota fiscal?', 'Em Recebimentos, a viagem aparece com "Envie a nota fiscal", o valor, o prazo e os dados da 645 Turismo para emitir. Emita pelo seu CNPJ (MEI ou empresa), informe o número e o valor e anexe o PDF ou a foto da nota.', 7, 1);
INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('faq', 'Nota fiscal e pagamento', 'Quando recebo o pagamento?', 'Depois que a equipe aprova a nota fiscal, Recebimentos mostra a previsão de pagamento, conforme o prazo de cada viagem/tour. O pagamento é feito por PIX ou transferência e o comprovante fica disponível em Recebimentos.', 8, 1);
INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('faq', 'Nota fiscal e pagamento', 'Minha nota ou meu relatório foi devolvido.', 'O motivo aparece na tela e no e-mail. Corrija e envie de novo pelo mesmo lugar: a nota em Recebimentos e o relatório na viagem/tour.', 9, 1);
INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('faq', 'Cadastro', 'Preciso atualizar meus dados, documentos ou PIX.', 'Em Perfil você atualiza dados pessoais, atuação, documentos e dados de recebimento a qualquer momento. Um documento novo substitui o anterior e é conferido pela equipe, sem bloquear seu cadastro. Se trocar o PIX com pagamento em andamento, a equipe é avisada.', 10, 1);

INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('guia_pratico', NULL, 'Mantenha a disponibilidade em dia', 'Em Disponibilidade, toque nos dias e marque se pode trabalhar (dia todo, manhã, tarde ou noite). Dá para marcar vários dias de uma vez.', 1, 1);
INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('guia_pratico', NULL, 'Responda os convites', 'Os convites aparecem em Hoje e em Viagens/Tours. Aceite para liberar o briefing completo.', 2, 1);
INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('guia_pratico', NULL, 'No dia: lista de passageiros', 'Chegue no horário de apresentação, abra a lista e faça o check-in de cada passageiro no embarque e o check-out no desembarque.', 3, 1);
INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('guia_pratico', NULL, 'Relatório e nota fiscal', 'No último dia, envie o relatório. Depois, envie a nota fiscal em Recebimentos e acompanhe o pagamento.', 4, 1);

INSERT INTO orientacoes (secao, categoria, titulo, conteudo, ordem, ativo) VALUES ('contato', 'Coordenação', 'Coordenação 645 Turismo', 'contato@645turismo.com.br · (11) 95250-4927 (WhatsApp)', 1, 1);
